language: python
sudo: false
python: 2.7
env:
  global:
    - PLANEMO_SKIP_REDUNDANT_TESTS=1
    - PLANEMO_ENABLE_POSTGRES_TESTS=1
    - PLANEMO_SKIP_GALAXY_CWL_TESTS=1
    - PLANEMO_TEST_WORKFLOW_RUN_PROFILE=travisworkflowtests
  matrix:
    - TOX_ENV=py34-gx-1801
    - TOX_ENV=py34-gx-master

install:
  - pip install tox coveralls

matrix:
  allow_failures:
    - env: TOX_ENV=py27-lint-docstrings

script: tox -e $TOX_ENV

after_success:
  - coveralls

services:
  - postgresql
