[pytest]
addopts = --verbosity=1 --ignore planemo/commands/cmd_test.py
markers =
    embedded_galaxy: tests requiring a package-installed embedded Galaxy runtime
    installed_galaxy: tests requiring a package-installed Galaxy runtime managed by Gravity
    tests_galaxy_branch: test against a specific Galaxy branch
