package:
  name: fleeqtk
  version: 1.4

source:
  fn: v1.4.tar.gz
  url: https://github.com/jmchilton/fleeqtk/archive/v1.4.tar.gz
  md5: 2c2df657f780ca0a8046518eb3f92a91

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib
  run:
    - zlib


about:
  home: https://github.com/jmchilton/fleeqtk
  license: MIT License
  summary: fleeqtk - those sequences are on fleeqtk

test:
  commands:
    - true
